// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFUUu-CJ902phDcK_BWuKR6fiUgwzXb9I',
    appId: '1:579775767696:web:4007e4df501939061d2415',
    messagingSenderId: '579775767696',
    projectId: 'mipripity-signup',
    authDomain: 'mipripity-signup.firebaseapp.com',
    storageBucket: 'mipripity-signup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFUUu-CJ902phDcK_BWuKR6fiUgwzXb9I',
    appId: '1:579775767696:android:4007e4df501939061d2415',
    messagingSenderId: '579775767696',
    projectId: 'mipripity-signup',
    storageBucket: 'mipripity-signup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUUu-CJ902phDcK_BWuKR6fiUgwzXb9I',
    appId: '1:579775767696:ios:4007e4df501939061d2415',
    messagingSenderId: '579775767696',
    projectId: 'mipripity-signup',
    storageBucket: 'mipripity-signup.appspot.com',
    iosBundleId: 'com.appfoundry.previewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFUUu-CJ902phDcK_BWuKR6fiUgwzXb9I',
    appId: '1:579775767696:ios:4007e4df501939061d2415',
    messagingSenderId: '579775767696',
    projectId: 'mipripity-signup',
    storageBucket: 'mipripity-signup.appspot.com',
    iosBundleId: 'com.appfoundry.previewer',
  );
}
